name: fl_business_card_core
description: Open-source & serverless Business Card generator, core in Dart for
  both Mobile & Web implementations.
version: 0.0.1
homepage: https://github.com/Floating-Dartists/fl_business_card_core

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.8.2
  mockito: ^5.1.0
  remove_from_coverage: ^2.0.0
  test: ^1.20.1

flutter: null
