name: fl_business_card_core
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Floating-Dartists/fl_business_card_core

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  remove_from_coverage: ^2.0.0

flutter: null
