name: Test workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - name: Install Dependencies 
      run: dart pub get
    - name: Analyze Code
      run: dart analyze
      working-directory: ./lib
    - name: Test
      run: dart test --coverage="coverage"
    # - name: Exclude generated files from coverage
    #   run: dart pub run remove_from_coverage -f coverage/lcov.info -r '\.g\.dart$'
    - name: Collect and report coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}